version: '3.8'

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "5000:80"
    volumes:
      - ./src:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/:/var/log/nginx/
    depends_on:
      - app
      - db

  #Database Service
  db:
    image : mysql
    container_name : db
    volumes:
      - .data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -proot"]
      timeout: 5s
      retries: 10

  # db:
  #   image: postgres
  #   container_name: postgres
  #   volumes:
  #     - ./postgresql/data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   environment: 
  #     POSTGRES_DB: blog
  #     POSTGRES_USER: root 
  #     POSTGRES_PASSWORD: password 

  # Application Service
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
      - ./lara-log:/var/www/storage/logs
    ports:
      - "9000:9000"
    working_dir: /var/www
    user: www-data:www-data
    depends_on:
      # - db
      db:
        condition: service_healthy

    command: bash start.sh

  #phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3400:80"
    depends_on:
      - db
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgAdmin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db 
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: hanieasemi76@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: password 