---
name: CI/CD Pipeline
on:
  push:
    branches: master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
        
    - name: SSH into server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /var/www/html/Laravel-Ecommerce-php8.0-working
          sudo docker-compose down
          sudo git pull origin master
          sudo docker-compose up --build -d
          echo "Done"

    - name: Check current user
      run: whoami
      
#     - name: Change working directory
#       run: cd /var/www/html/Laravel-Ecommerce-php8.0-working
      
#     - name: Bring down containers
#       run: sudo docker-compose down
      
#     - name: Git Pull
#       run: sudo git pull origin master
      
#     - name: Spin up containers
#       run: sudo docker-compose up --build -d
      
#     - name: Done
#       run: echo "Done"
