---
name: CI/CD Pipeline
on:
  push:
    branches: master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
        
    - name: SSH into server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          docker-compose --version
          cd /var/www/html/Laravel-Ecommerce-php8.0-working
          sudo docker-compose down
          sudo git pull origin master
          sudo docker-compose build
          sudo docker-compose up -d
          echo "Done"

    - name: Check current user
      run: whoami

    - name: Check container status
      run: |
        if docker ps --filter "name=nginx" --format "{{.Names}}" | grep -q "nginx"; then
          echo "Container is running"
        else
          echo "Container is not running"
        fi
